#include "aethon/protocol/packet.hpp"
#include "aethon/codec/binary_reader.hpp"
#include "aethon/codec/binary_writer.hpp"
#include "aethon/codec/crc.hpp"
#include "aethon/common/error.hpp"
#include <limits>
#include <utility>
namespace aethon::protocol {
namespace {
enum Section : std::uint8_t { fragment_section = 1, route_section = 2, capabilities_section = 3, extension_section = 4 };
ProtocolVersion version_from(std::uint8_t raw) { if (raw < 1 || raw > 3) throw Error(ErrorCode::unsupported_version, "unsupported protocol version"); return static_cast<ProtocolVersion>(raw); }
PacketKind kind_from(std::uint8_t raw) { if (raw < 1 || raw > 5) throw Error(ErrorCode::malformed_packet, "unknown packet kind"); return static_cast<PacketKind>(raw); }
void write_fragment(codec::BinaryWriter& w, const FragmentInfo& f) { w.u32(f.stream_id); w.u16(f.sequence); w.u16(f.count); }
FragmentInfo read_fragment(codec::BinaryReader& r) { FragmentInfo f{r.u32(), r.u16(), r.u16()}; if (f.count == 0 || f.sequence >= f.count) throw Error(ErrorCode::malformed_packet, "invalid fragment coordinates"); return f; }
void write_route(codec::BinaryWriter& w, const RoutingInfo& route) { w.u16(route.region); w.u16(route.collector); w.u8(route.priority); if (route.relay_path.size() > 32) throw Error(ErrorCode::invalid_argument, "relay path is too deep"); w.u8(static_cast<std::uint8_t>(route.relay_path.size())); for (auto hop : route.relay_path) w.u16(hop); }
RoutingInfo read_route(codec::BinaryReader& r) { RoutingInfo route; route.region = r.u16(); route.collector = r.u16(); route.priority = r.u8(); auto hops = r.u8(); if (hops > 32) throw Error(ErrorCode::malformed_packet, "relay path is too deep"); for (std::uint8_t i = 0; i < hops; ++i) route.relay_path.push_back(r.u16()); return route; }
void write_capabilities(codec::BinaryWriter& w, const DeviceCapabilities& caps) { std::uint8_t flags = 0; flags |= caps.supports_compression ? 1 : 0; flags |= caps.supports_encryption ? 2 : 0; flags |= caps.has_gps_time ? 4 : 0; w.u8(flags); w.u16(caps.max_payload); if (caps.sensor_bands.size() > 16) throw Error(ErrorCode::invalid_argument, "too many sensor bands"); w.u8(static_cast<std::uint8_t>(caps.sensor_bands.size())); for (const auto& band : caps.sensor_bands) w.string(band); }
DeviceCapabilities read_capabilities(codec::BinaryReader& r) { DeviceCapabilities caps; auto flags = r.u8(); caps.supports_compression = (flags & 1) != 0; caps.supports_encryption = (flags & 2) != 0; caps.has_gps_time = (flags & 4) != 0; caps.max_payload = r.u16(); auto count = r.u8(); if (count > 16) throw Error(ErrorCode::malformed_packet, "too many bands"); for (std::uint8_t i = 0; i < count; ++i) caps.sensor_bands.push_back(r.string(64)); return caps; }
void write_section(codec::BinaryWriter& out, std::uint8_t id, const Bytes& section) { if (section.size() > std::numeric_limits<std::uint16_t>::max()) throw Error(ErrorCode::invalid_argument, "packet section exceeds wire limit"); out.u8(id); out.u16(static_cast<std::uint16_t>(section.size())); out.bytes(section); }
} // namespace
NegotiatedProtocol negotiate(ProtocolVersion local_max, const DeviceCapabilities& remote) { return NegotiatedProtocol{local_max, remote.supports_compression, remote.supports_encryption}; }
Bytes encode_payload_sections(const Packet& packet) { codec::BinaryWriter out; if (packet.fragment) { codec::BinaryWriter s; write_fragment(s, *packet.fragment); write_section(out, fragment_section, s.buffer()); } if (packet.route) { codec::BinaryWriter s; write_route(s, *packet.route); write_section(out, route_section, s.buffer()); } if (packet.capabilities) { codec::BinaryWriter s; write_capabilities(s, *packet.capabilities); write_section(out, capabilities_section, s.buffer()); } for (const auto& ext : packet.extensions) { codec::BinaryWriter s; s.u16(ext.type); s.u16(static_cast<std::uint16_t>(ext.value.size())); s.bytes(ext.value); write_section(out, extension_section, s.buffer()); } out.u8(0); return out.take(); }
void decode_payload_sections(Packet& packet, std::span<const std::uint8_t> sections, DecodeOptions options) { codec::BinaryReader r(sections); while (!r.empty()) { auto id = r.u8(); if (id == 0) { if (!r.empty()) throw Error(ErrorCode::malformed_packet, "trailing section bytes"); return; } auto len = r.u16(); auto body = r.bytes(len); codec::BinaryReader section(body); switch (id) { case fragment_section: packet.fragment = read_fragment(section); break; case route_section: packet.route = read_route(section); break; case capabilities_section: packet.capabilities = read_capabilities(section); break; case extension_section: { ExtensionHeader ext; ext.type = section.u16(); auto size = section.u16(); ext.value = section.bytes(size); packet.extensions.push_back(std::move(ext)); break; } default: if (options.require_known_extensions) throw Error(ErrorCode::malformed_packet, "unknown section"); break; } if (!section.empty()) throw Error(ErrorCode::malformed_packet, "section tail not consumed"); } throw Error(ErrorCode::malformed_packet, "missing section terminator"); }
Bytes encode_packet(const Packet& packet) { codec::BinaryWriter body; body.u8(static_cast<std::uint8_t>(packet.version)); body.u8(static_cast<std::uint8_t>(packet.kind)); body.u64(packet.device); body.u64(packet.timestamp_ns); body.u32(packet.sequence); body.u8(static_cast<std::uint8_t>(packet.compression)); body.u8(static_cast<std::uint8_t>(packet.encryption)); auto sections = encode_payload_sections(packet); body.u32(static_cast<std::uint32_t>(sections.size())); body.bytes(sections); body.u32(static_cast<std::uint32_t>(packet.payload.size())); body.bytes(packet.payload); codec::BinaryWriter frame; frame.u32(packet_magic); frame.u32(static_cast<std::uint32_t>(body.buffer().size())); frame.bytes(body.buffer()); frame.u32(codec::crc32c(frame.buffer())); return frame.take(); }
Packet decode_packet(std::span<const std::uint8_t> frame, DecodeOptions options) { if (frame.size() < 12 || frame.size() > options.max_packet_size) throw Error(ErrorCode::malformed_packet, "packet length outside bounds"); auto expected_crc = codec::crc32c(frame.subspan(0, frame.size() - 4)); codec::BinaryReader envelope(frame); if (envelope.u32() != packet_magic) throw Error(ErrorCode::malformed_packet, "packet magic mismatch"); auto body_len = envelope.u32(); if (body_len + 12 != frame.size()) throw Error(ErrorCode::malformed_packet, "packet length mismatch"); auto body = envelope.bytes(body_len); if (envelope.u32() != expected_crc) throw Error(ErrorCode::checksum_mismatch, "packet crc mismatch"); codec::BinaryReader r(body); Packet packet; packet.version = version_from(r.u8()); packet.kind = kind_from(r.u8()); packet.device = r.u64(); packet.timestamp_ns = r.u64(); packet.sequence = r.u32(); packet.compression = static_cast<CompressionMode>(r.u8()); packet.encryption = static_cast<EncryptionMode>(r.u8()); auto section_len = r.u32(); decode_payload_sections(packet, r.bytes(section_len), options); auto payload_len = r.u32(); packet.payload = r.bytes(payload_len); if (!r.empty()) throw Error(ErrorCode::malformed_packet, "trailing packet bytes"); return packet; }
} // namespace aethon::protocol
